### ISSUE TITLE
Problem with encoder exiting silently with no output under Windows

### ISSUE THREAD

**Issue by Jamaika1** [fraunhoferhhi/vvenc#155] opened 2022-04-20 05:22 UTC
The encoder doesn't want to create the file. I don't know what I'm doing wrong.
VVEncoderApp.exe -i "113.yuv" -o "output_10bit.vvc" -v 5 -t 4 -s 1280x720 -r 29 -c yuv420 -g 16 -ip 256 --internal-bitdepth 10 --bitrate 3Mbps -f 200 --passes 1 --preset medium --level 6.3 --tier main 
https://www.sendspace.com/file/839893

**Comment by adamjw24** [comment] 2022-04-20 07:57
What is the VVEncoderApp.exe? Which of our encoders is that?

**Comment by adamjw24** [comment] 2022-04-20 08:57
Please also attach log of the encoding

**Comment by Jamaika1** [comment] 2022-04-20 16:23
This is the vvenc version [303ade3](https://github.com/fraunhoferhhi/vvenc/commit/303ade3460e06ee4ecdfc464f0dc356e5d5914d5)

**Comment by adamjw24** [comment] 2022-04-23 17:05
Which of the two executable tho? Please provide encoder log

**Comment by Jamaika1** [comment] 2022-04-25 15:58
```
C:\Users\WWW\Downloads\hevc\image3>VVEncoderApp.exe -i "113.yuv" -o "output_10bit.vvc" -v 5 -t 4 -s 1280x720 -r 29 -c yuv420 -g 16 -ip 256 --internal-bitdepth 10 --bitrate 3Mbps -f 200 --passes 1 --preset medium --level 6.3 --tier main
vvencapp: Fraunhofer VVC Encoder ver. 1.4.0 [Windows][GCC 12.0.1][64 bit][SIMD=NA]
CODING TOOL CFG: CTU128 QT44BTT21 IBD:1 CIP:0 SAO:1 ALF:1 (NonLinLuma:0 NonLinChr:0) CCALF:1 Tiles:1x1 Slices:1 WPP:0 WPP-Substreams:1 TMVP:1 DQ:1 SDH:0 CST:1 BDOF:1 DMVR:1 MTSImplicit:1 SBT:0 JCbCr:1 CabacInitPresent:0 AMVR:5 SMVD:3 LMCS:2 (Signal:SDR Opt:0) CIIP:0 MIP:1 AFFINE:2 (PROF:1, Type:1) MMVD:3 DisFracMMVD:1 SbTMVP:1 GPM:3 LFNST:1 MTS:0 ISP:3 TS:2 TSLog2MaxSize:4 useChromaTS:0 BDPCM:2 IBC:2 BCW:0
ENC. ALG. CFG: QPA:1 HAD:1 RDQ:1 RDQTS:1 ASR:1 MinSearchWindow:96 RestrictMESampling:0 EDO:2 MCTF:2
PRE-ANALYSIS CFG: STA:1 LeadFrames:0 TrailFrames:0
FAST TOOL CFG: ECU:0 FEN:1 FDM:1 FastSearch:4 (SCC:2) LCTUFast:1 FastMrg:2 PBIntraFast:1 AMaxBT:0 FastQtBtEnc:1 ContentBasedFastQtbt:0 FastMIP:4 FastIntraTools:1 IntraEstDecBit:2 FastLocalDualTree:1 IntegerET:0 FastSubPel:1 QtbttExtraFast:3 FastTTSplit:0 IBCFastMethod:3 FIM:0 ALFSpeed:0 QuantThr: 4
RATE CONTROL CFG: RateControl:1 Passes:1 Pass:-1 TargetBitrate:3000000 RCInitialQP:0 RCForceIntraQP:0 LookAhead:1
PARALLEL PROCESSING CFG: NumThreads:4 MaxParallelFrames:4 WppBitEqual:1 WF:0

started @ Mon Apr 25 17:56:42 2022


C:\Users\WWW\Downloads\hevc\image3>

**Comment by adamjw24** [comment] 2022-04-26 16:10
So just for my understanding. You compiled without SIMD support, you are using the simple app, and the encoder exits without an error before doing anything.

I'll have a look soon.

FYI, for 720p at 3mbps, there is no need to use level 6.3. Some decoders might reject such file.

**Comment by adamjw24** [comment] 2022-05-03 08:20
Hmm, cannot reproduce with the newest HEAD, could you recheck?

Btw, there is no way to compile VVenC with TARGET_SIMD_X86 disabled, so I assume you changed the sources? Maybe this is what introduced the problem?

**Comment by Jamaika1** [comment] 2022-05-03 15:11
My tests and latest codecs.
https://www.sendspace.com/file/204ph0

I use gcc 12.0.1 20220429. http://msystem.waw.pl/x265/mingw-gcc1201-20220429.7z
I use plugins for gcc thread/mutex/future/condition_variable 
https://github.com/Jamaika1/mingw_std_threads
Btw. vvenc/dec compiled without any changes and without TARGET_SIMD_X86. Previous versions of vvc worked.
Level you can use auto. Same effect.

Btw. A new library on github has appeared uvg266. It works. The problem is that it isn't compatible with fraunhoferhhi.

**Comment by adamjw24** [comment] 2022-05-03 18:04
I tend to not download random files from the internet. I did this time, and was warned about possible virus by 7zip. So I guess I will go back to not doing it.

Please always provide all relevant information in the issue, as text.

Btw. vvenc/dec without TARGET_SIMD_X86 is not without any changes. At least for VVenC its not an external build options, so disabling it implies you changed the code or build system. Just for my interest, why would you even do that? You can disable those at runtime.

Since you patched your build process, I would suggest checking if maybe that's the problem.

How do you mean uvg266 is not compatible with fraunhoferhhi? I did some quick tests and vvdec can decode it just fine.

**Comment by adamjw24** [comment] 2022-05-03 18:13
> How do you mean uvg266 is not compatible with fraunhoferhhi? I did some quick tests and vvdec can decode it just fine.

Nevermind, saw the issue in their repo.

**Comment by adamjw24** [comment] 2022-05-20 08:44
Cannot reproduce, the build was heavily patched, and no additional info provided. Closing.

**Closed by adamjw24** 2022-05-20 08:44 UTC
