### ISSUE TITLE
VVC not building with media-autobuild_suite?

### ISSUE THREAD

**Issue by JohnTravolski** [fraunhoferhhi/vvenc#324] opened 2023-10-20 16:24 UTC
I tried to create an ffmpeg build with VVC for Windows following instructions referencing the media autobuild suite: https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#windows

However, after following the instructions and attempting multiple times, the output binary does not include VVC. I noticed during my latest attempt media-autobuild_suite was outputting these messages:

![image](https://github.com/fraunhoferhhi/vvenc/assets/36255053/984afc9e-df99-4e6b-9134-5bd37e122ec6)

Perhaps I configured something wrong, but I'm not sure. I included logs and other relevant files in the attached zip. Any idea what's wrong?

[vvc_testing.zip](https://github.com/fraunhoferhhi/vvenc/files/13056381/vvc_testing.zip)

**Comment by lehmann-c** [comment] 2023-10-26 14:37
The patches are not working properly anymore.

You can set ffmpeg to the last working revision `9413bdc381` in the ini-file
`media-autobuild_suite/build/media-autobuild_suite.ini`:
`ffmpegPath=https://git.ffmpeg.org/ffmpeg.git#9413bdc381`

But as quite a lot of dependent packages also changed since spring 2023, it is expected fail to build.
You can try to play around with the `ffmpegPath`, but if you revert the ffmpeg revision you also have to disable some packages in the file `build/ffmpeg_options.txt` and adapt quite a lot of revisions of dependent packages of repositories defined in `build/media-suite_deps.sh`

Best option is to wait for new patchset or hope that the patches will me accepted and merged into the main branch.

**Comment by JohnTravolski** [comment] 2023-11-02 03:58
Aw man

**Comment by lehmann-c** [comment] 2023-11-03 10:45
Good news - a new patchset for vvenc/vvdec has just been submitted.
The VVenC wiki is already updated and you can give it another try with the latest ffmpeg version.

**Comment by JohnTravolski** [comment] 2023-11-06 14:23
> Good news - a new patchset for vvenc/vvdec has just been submitted. The VVenC wiki is already updated and you can give it another try with the latest ffmpeg version.

Awesome, I actually got it working! Although media autobuild suite was having its own set of issues and I had to disable the following in the `media-autobuild_suite.ini` config file:

```
libavif=2
jpegxl=2
```
and I had to disable a few things in the ffmpeg_options.txt file as well:
```
--disable-libplacebo
--disable-libjxl
--disable-doc
```

**Comment by lehmann-c** [comment] 2023-11-07 08:14
Thanks for the feedback.
I added a section in the wiki concerning media_suite troubleshooting:
[https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#troubleshooting-media-autobuild-suite](url)

**Comment by adamjw24** [comment] 2023-11-07 09:06
Thanks for reporting. Glad the issue is now resolved from our side. Closing for now

**Closed by adamjw24** 2023-11-07 09:06 UTC
Labels: question, build
