### ISSUE TITLE
Bad quality when use VVC

### ISSUE THREAD

**Issue by phanluchoafptpoly** [fraunhoferhhi/vvenc#315] opened 2023-09-05 04:44 UTC
Hello,

I have try to use this codec for encode my video for give the optimize file size and quality but when I use this I see that the quality after it encoded is so bad, so blur, I have use the FFmpeg that have VVC for encode it and it same. I have try using FastFlix for  change the default ffmpeg to ffmpeg that have this codec for easier to use and not use any command to it. This is the settings that I use for encode (i have try to change preset to slower for hope getting high quality but it the same, so blur).

![image](https://github.com/fraunhoferhhi/vvenc/assets/144089055/a8b0985b-29dc-4b87-950f-9bc09512f84b)

Thanks!

**Comment by adamjw24** [comment] 2023-09-06 10:35
Can you show some actual issues?

Best would be providing the raw video and the exact VVenC cmd line. And even better a command line for some other encoder that works better.

**Comment by phanluchoafptpoly** [comment] 2023-09-06 10:58
Sure,

Here is the video that I use for encoding (otherwise, i use FastFlix for doing mp4 input) so I will send you my mp4 video file and command that use for encode show on FastFlix:

VIdeo link: [https://drive.google.com/file/d/1LVPaV0GmcL2d5b_v4SJ0v1h2GixYIoqY/view?usp=sharing]

FFMPEG path (I change it from FastFlix for apply VVC): 
![image](https://github.com/fraunhoferhhi/vvenc/assets/144089055/a4465fef-2b92-4240-9a36-71f8b0d9a09b)

![image](https://github.com/fraunhoferhhi/vvenc/assets/144089055/d577e1d5-a80f-4f93-b046-8e4d76d82588)


Command that I use: "D:\ffmpeg.exe"   -y      -i "D:\1.mp4"   -max_muxing_queue_size 1024    -filter_complex "[0:0]crop=3840:1812:0:174[v]" -map "[v]"  -c:v libvvenc -pix_fmt yuv420p10le     -tier:v high -levelidc 5.1    -qp:v 20 -preset:v slower  -metadata:s:v rotate=0  -map_metadata 0 -map_chapters -1  -map 0:1 -metadata:s:1 title="" -metadata:s:1 handler="" -metadata:s:1 language=eng -c:1 eac3 -b:1 128k   -disposition:1 default -default_mode infer_no_subs  "D:\1\1-fastflix-a26d.mkv" (This is the command shows on FastFlix)

Thanks!

**Comment by phanluchoafptpoly** [comment] 2023-09-07 04:53
@adamjw24 Do you have any idea ?

**Comment by phanluchoafptpoly** [comment] 2023-09-07 05:10
vp9, av1, h264 and h265 is ok for me but when i try to use this new codec i have that issue

**Comment by adamjw24** [comment] 2023-09-07 07:09
Have patience. It will take come time

**Comment by lehmann-c** [comment] 2023-09-11 10:37
It seems to be a bug in the VVenC ffmpeg integration, as constant QP mode is not working properly.
The translated ffmpeg command line will still use VBR mode with 200kbit/s.
This happens as 200kbit/s is the default video bitrate and as long as the video bitrate is not set to 0, the VBR mode is used.

You can force the fix QP mode by setting   `bitrate=0`
in the `Advanced` section under `Additional vvc params`

To verify the the settings you also can increase the vvenc verbosity: `verbosity=details:bitrate=0` to log what parameters are set in VVenC.

**Comment by phanluchoafptpoly** [comment] 2023-09-11 12:00
Thanksss , i will try it

Vào Th 2, 11 thg 9, 2023 lúc 17:37 Christian Lehmann <
***@***.***> đã viết:

**Comment by phanluchoafptpoly** [comment] 2023-09-11 13:21
> It seems to be a bug in the VVenC ffmpeg integration, as constant QP mode is not working properly. The translated ffmpeg command line will still use VBR mode with 200kbit/s. This happens as 200kbit/s is the default video bitrate and as long as the video bitrate is not set to 0, the VBR mode is used.
> 
> You can force the fix QP mode by setting `bitrate=0` in the `Advanced` section under `Additional vvc params`
> 
> To verify the settings you also can increase the vvenc verbosity: `verbosity=details:bitrate=0` to log what parameters are set in VVenC.

How about with 2 pass bitrate ? 

![image](https://github.com/fraunhoferhhi/vvenc/assets/144089055/67f05371-e5d9-4b1a-bc9d-1ec2a3f507d2)

When I use, i dont see any value on log file in pass 1

**Comment by phanluchoafptpoly** [comment] 2023-09-11 15:42
> It seems to be a bug in the VVenC ffmpeg integration, as constant QP mode is not working properly. The translated ffmpeg command line will still use VBR mode with 200kbit/s. This happens as 200kbit/s is the default video bitrate and as long as the video bitrate is not set to 0, the VBR mode is used.
> 
> You can force the fix QP mode by setting `bitrate=0` in the `Advanced` section under `Additional vvc params`
> 
> To verify the settings you also can increase the vvenc verbosity: `verbosity=details:bitrate=0` to log what parameters are set in VVenC.

The quality is better after add those params, thanks!

**Comment by adamjw24** [comment] 2023-09-12 07:05
I assume the issue is resolved? Closing

**Comment by adamjw24** [comment] 2023-09-12 08:42
Oh, sorry for too eager closing. Let me know when all questions are resolved

**Comment by phanluchoafptpoly** [comment] 2023-09-12 10:11
> Oh, sorry for too eager closing. Let me know when all questions are resolved

It fixed, thanks for support

**Closed** 2023-09-12 10:11 UTC
Labels: question, library

**Comment by phanluchoafptpoly** [comment] 2023-09-16 05:55
> Oh, sorry for too eager closing. Let me know when all questions are resolved

Hello, do u know how to keep HDR Information when encode this ?
