### ISSUE TITLE
Blurriness than x265 in motion

### ISSUE THREAD

**Issue by ZenKiyoshi** [fraunhoferhhi/vvenc#133] opened 2022-02-05 04:22 UTC
Windows, latest git master

my command
`ffmpeg -i "Original_Video.mkv" -pix_fmt yuv420p10le -f yuv4mpegpipe -strict -1 - | vvencapp -i - --y4m --preset fast -c yuv420_10 -q 18 --qpa 0 -o "VVenC_fast_qpa0_q18.266"`

At static scene, VVenC is better than x265
but in motion VVenC is blurry even when --qpa 0 
I use --qpa 0 to make comparision since --qpa 1 is much worst in motion
VVenC preset fast and medium

https://slow.pics/c/HJncei1F

https://slow.pics/c/yooInZf5

This frame is hard, the middle cloud appears only in 1 frame.
x265 could keep some details, but VVenC fast and medium completely blur it.
https://slow.pics/c/c9LbCbKr

This frame is strange, this is near static scene, VVenC did very good than x265 at most part of the frame
But at the bottom right corner where has some moving car, at this part VVenC is blurry, lost detail than x265.
https://slow.pics/c/ZG4IcvMp
It look like if any part of the frame have motion in it, this part will be blurred though the frame is static scene

Origin and encoded video: https://drive.google.com/drive/folders/1fXGA6UAhLBGvqDTgEDric_IUh6tOcEq3?usp=sharing

**Comment by ZenKiyoshi** [comment] 2022-02-07 09:15
The blocking artifacts I mentioned ago, they could be made by jpeg compression, so I change all screenshots to png format.

**Comment by adamjw24** [comment] 2022-02-07 09:22
Again, what are the resolution, and bitrates used for x265 and VVenC?

Did you made a comparison of the content as a video? QPA tries to adhere to HVS of how video is perceived, so viewing static frames kind of misses the point. I don't want to say your point is invalid, I just want to have all the data.

**Comment by ZenKiyoshi** [comment] 2022-02-07 09:37
res: 1920x1080
bitrate:
x265: 1760 kb/s
VVenC medium are same around
VVenC fast little bit higher bitrate
I try adjusting VVenC -q parameter to achive same filesize

> Did you view the video as a video? Are the artifacts still disturbing?
Yes I view video normally and of cource I am hard to see the artifacts.

The most different come frome motion scenes.

**Comment by adamjw24** [comment] 2022-02-07 14:13
Closing as duplicate of #132

**Closed by adamjw24** 2022-02-07 14:13 UTC
Labels: duplicate, question, library
