### ISSUE TITLE
Be able to request a keyframe on demand

### ISSUE THREAD

**Issue by carlosfg-flu** [fraunhoferhhi/vvenc#481] opened 2024-12-04 09:15 UTC
It would be useful to be able to request a key-frame to the encoder. For example, in network streaming scenarios like when using webrtc.

**Comment by adamjw24** [comment] 2024-12-04 09:43
Duplicate of https://github.com/fraunhoferhhi/vvenc/issues/311

VVenC cannot be used in webrtc scenarios, because it does not support real time encoding.

**Closed by adamjw24** 2024-12-04 09:43 UTC
Labels: duplicate, library
