### ISSUE TITLE
code error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by soaringleefighting** [fraunhoferhhi/vvenc#76] opened 2021-07-25 02:40 UTC
vvencapp encontered segmentation fault(core dumped) when encoding POC 144 using following parameter:
-c yuv420  -r 30 -rt idr  -g 16  -ip 160  --preset faster -b 0 --qp 22  --threads 1  -o out.266  -v 6

**Comment by adamjw24** [comment] 2021-07-25 10:53
Is the input video available somewhere? Some more information would be very helpful.

Or does that always happen with long intra period IDR encoding?

I'll do some testing in the coming days. Would appreciate some pointers on where to look.

**Comment by soaringleefighting** [comment] 2021-07-26 01:31
Yes, the input video is available. Here I just list the key parameters. According to my experiments, it definitely happen with long intra period IDR encoding.
But when I modified '--ip 160'  to '--ip 96', it can run normally.

**Comment by adamjw24** [comment] 2021-07-26 10:11
Would you mind sharing the video?

**Comment by soaringleefighting** [comment] 2021-07-26 11:07
The video is from CTC (common test conditions), for example BQMall_832x480_60.yuv.

**Comment by adamjw24** [comment] 2021-07-29 11:26
We cannot reproduce the problem. I tried with both v1.0.0 and current head and it works fine.

What CPU are you running on? What SIMD settings are being used? Could you maybe paste the log?

**Comment by soaringleefighting** [comment] 2021-08-11 03:25
CPU: Intel Core i3-9100F
SIMD: AVX2

Another,  I test the newest verison(v1.1.0), it works fine.

**Comment by adamjw24** [comment] 2021-08-11 08:31
Thanks. Closing the issue.

**Closed by adamjw24** 2021-08-11 08:31 UTC
