### ISSUE TITLE
build for Windows

### ISSUE THREAD

**Issue by Xtof35** [fraunhoferhhi/vvenc#23] opened 2021-03-02 16:25 UTC
Hello

I tried to build for windows after installing cmake , Visual Studio 19, and gnuwin32 with make
That give me this error 
Sorry, I'm a newbie but I really want to test VVC on windows

make install-release
process_begin: CreateProcess(NULL, cmake -P cmake/modules/vvencNumCores.cmake, ...) failed.
cmake -S . -B build/static -A x64 -DCMAKE_CONFIGURATION_TYPES=Debug\;Release\;RelWithDebInfo
process_begin: CreateProcess(NULL, cmake -S . -B build/static -A x64 -DCMAKE_CONFIGURATION_TYPES=Debug;Release;RelWithDebInfo, ...) failed.
make (e=2): Le fichier spécifié est introuvable.
make: *** [build/static] Erreur 2

regards

**Comment by adamjw24** [comment] 2021-03-02 16:59
It seems as if some of the programs were not in the path.

When you call "cmake.exe" in the terminal, what is the output?

Best regards

**Comment by Xtof35** [comment] 2021-03-03 08:35
Thanks for your answer
That right cmake, wasn't in the path
But now, it's done and I still have an issue

make install-release
cmake -S . -B build/static -A x64 -DCMAKE_CONFIGURATION_TYPES=Debug\;Release\;RelWithDebInfo
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:13 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/cnelson/Downloads/vvenc-master/build/static/CMakeFiles/CMakeOutput.log".
make: *** [build/static] Erreur 1

**Comment by adamjw24** [comment] 2021-03-04 12:31
Thats strange. It seems your cmake generates the project for Makefiles instead of Visual Studio.

Since you are on windows, you could try skipping the makefile layer and go directly with CMake (once the project is generated you will probably be integrating with it through Visual Studio either way).

To do this, create a build directory in the vvenc source path, go there with your console and call:

`C:\Your\Directory\vvenc\build>cmake .. -G "Visual Studio 16 2019" -DCMAKE_CONFIGURATION_TYPES=Debug;Release;RelWithDebInfo`

You could also do this from the CMakeGUI, which would ask you what generator to use.

**Comment by 1480c1** [comment] 2021-03-04 17:59
> Thats strange. It seems your cmake generates the project for Makefiles instead of Visual Studio.

from what I know, cmake usually skips vs if it doesn't detect a vs installation

**Comment by adamjw24** [comment] 2021-04-29 16:03
Closing, cannot reproduce and no further feedback.

**Closed by adamjw24** 2021-04-29 16:03 UTC
