### ISSUE TITLE
How to properly encode and decode YUV?

### ISSUE THREAD

**Issue by borneq** [fraunhoferhhi/vvenc#154] opened 2022-04-18 09:03 UTC
U test on foreman.yuv from http://www.hlevkin.com/hlevkin/TestVideo/
 - ./vvencapp -s 352x288 -i ./foreman.yuv --output=foreman.266
 - ./vvdecapp -b foreman.266 --y4m -o foreman.y4m

Output file y4m is twice larger than input yuv.
Next I view this with simple viewer yay:
- ./yay foreman.y4m 

Images are green and bad

The same if I encode+decode foreman_cif.y4m which has header

**Comment by Jamaika1** [comment] 2022-04-18 09:25
ffmpeg.exe -loglevel error -i "input.mp4" -an -f rawvideo -frames 1000 -vf scale=1280:720:in_color_matrix=rgb:in_range=full:out_color_matrix=rgb:out_range=full,format=yuv420p 113.yuv

VVEncoderApp.exe -i "113.yuv" -o "output_10bit.vvc" -v 5 -t 4 -s 1280x720 -r 29 -c yuv420 -g 32 -ip 256 --internal-bitdepth 10 --bitrate 3Mbps --passes 1 -f 1000 --preset medium --level 6.3 --tier high 

xeve_app.exe -i "113.yuv" -o "output_10abit.evc" --info 0 -v 3 -d 8 -m 4 -w 1280 -h 720 -z 29 -b 15 -I 256 --input-csp 1 --codec-bit-depth 10 --rc-type 1 --bitrate 3Mbps --frames 1000 --preset medium --level-idc 6.3 --profile main

**Comment by adamjw24** [comment] 2022-04-19 08:20
> ffmpeg.exe -loglevel error -i "input.mp4" -an -f rawvideo -frames 1000 -vf scale=1280:720:in_color_matrix=rgb:in_range=full:out_color_matrix=rgb:out_range=full,format=yuv420p 113.yuv
> 
> VVEncoderApp.exe v1.4.0-[213c1a5](https://github.com/fraunhoferhhi/vvdec/commit/213c1a5112a6bb519932995a892374aa353dd98b) xevd.exe v0.3.2-[6d729ab](https://github.com/mpeg5/xevd/commit/6d729ab57817ee604a11eaeb1cd9d01e8d53d874) openvvc.exe v1.1.0-dev-[2dde386](https://github.com/OpenVVC/OpenVVC/commit/2dde386df642e3a6636656d8bf547d48282f5519)
> 
> VVEncoderApp.exe -i "113.yuv" -o "output_10bit.vvc" -v 5 -t 4 -s 1280x720 -r 29 -c yuv420 -g 32 -ip 256 --internal-bitdepth 10 --bitrate 3Mbps --passes 1 -f 1000 --preset medium --level 6.3 --tier high
> 
> xeve_app.exe -i "113.yuv" -o "output_10bit.evc" --info 0 -v 3 -d 8 -m 4 -w 1280 -h 720 -z 29 -b 15 -I 256 --input-csp 1 --codec-bit-depth 10 --rc-type 1 --bitrate 3Mbps --frames 1000 --preset medium --level-idc 6.3 --profile main
> 
> Decoding video...
> 
> InternalBitDepth can't be greater than 10. Y4M files {yuv4mpegpipe} doesn't have color matrix and range information {XYSCSS=420P XCOLORRANGE=FULL}.
> 
> DecoderApp_REXT_360.exe -b output_10bit.vvc -o output_vvc_10bit.yuv -d 10 VVDecoderApp.exe -v 6 -b output_10bit.vvc -o output_vvc_10bit.y4m -t 4 --y4m VVDecoderApp.exe -v 6 -b output_10bit.vvc -o output_vvc_10bit.yuv -t 4 xevd_app.exe -v 2 -i output_10bit.evc -o output_evc_10bit.yuv -m 4 --output-bit-depth 10 openvvc -i output_10bit.evc -o output_vvc_10bit.yuv {theoretically}
> 
> [mpeg5/xevd#25](https://github.com/mpeg5/xevd/issues/25)

What are you even saying?

**Comment by adamjw24** [comment] 2022-04-19 08:24
Duplicate of #152, #26. Please see https://github.com/fraunhoferhhi/vvdec/issues/4

**Closed by adamjw24** 2022-04-19 08:24 UTC
Labels: duplicate
